- name: Setup server for me
  hosts: webservers
  vars_files:
    - ../vars.yml
  become: true
  roles:
    - role: start
    - role: passwords_rules
    - role:  firewall
      firewall_ports: "{{ access_port }}"
      firewall_allow_icmp: true
    - role: fail2ban
    - role: nginx
    - role: certbot
    - role: postgres
    - role: postgres_db
      postgres_db_name: "{{ postgres_db_name }}"
      postgres_db_user: "{{ postgres_db_user }}"
      postgres_db_password: "{{ postgres_db_password }}"
    - role: ssh
      ssh_port: "{{ custom_ssh_port }}"
